name: Deploy to Production (v2.1.x)

on:
  workflow_dispatch:
    branches:
      - v2.1.x
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout Personal website project
      - uses: actions/checkout@v3

      - uses: ./.github/actions/configure-ssh
        with:
          id-rsa: ${{ secrets.PERSONAL_PRIVATE_ID_RSA }}
          host: ${{ secrets.PERSONAL_PRODUCTION_HOST }}

      - uses: ./.github/actions/build
        with:
          env: production
          php-version: '8.2.7'
          node-version: '18.16.0'

      - name: Remove unnecessary production/staging files
        run: |
          for f in $(find "." -maxdepth 1 -name '.*' ! -name '.' ! -name '..' ! -name '.github'); do rm -fR $f; done;
          rm -fR ./resources/js;
          rm -fR ./resources/sass;
          rm -fR ./tests;
          rm -f  ./.env*;
          rm -f  ./composer.*;
          rm -f  ./docker-compose.yml;
          rm -f  ./LICENSE;
          rm -f  ./package.json;
          rm -f  ./phpunit.xml;
          rm -f  ./README.md;
          rm -f  ./vite.config.js;
          rm -f  ./yarn.lock;
        shell: bash

      - name: Zip files for transfer
        run: cd .. && tar -cjf Personal.tar.bz2 Personal
        shell: bash

      - name: Backup current site
        run: ssh admin@${{ secrets.PERSONAL_PRODUCTION_HOST }} 'sudo cp -a /var/www/personal /tmp/personal.bak'
        shell: bash

      - name: Send project to server
        run: "scp -i ~/.ssh/id_rsa ../Personal.tar.bz2 admin@${{ secrets.PERSONAL_PRODUCTION_HOST }}:/tmp/Personal.tar.bz2"
        shell: bash

      - name: Unwrap project on server
        run: ssh admin@${{ secrets.PERSONAL_PRODUCTION_HOST }} 'cd /tmp && tar -xf Personal.tar.bz2'
        shell: bash

      - name: Create storage link
        run: ssh admin@${{ secrets.PERSONAL_PRODUCTION_HOST }} 'cd /tmp/Personal/public && ln -s ../storage/app/public storage'
        shell: bash

      - name: Fetch .env
        run: ssh admin@${{ secrets.PERSONAL_PRODUCTION_HOST }} 'sudo cp /var/www/personal/.env /tmp/Personal'
        shell: bash

      - name: Fix ownership
        run: ssh admin@${{ secrets.PERSONAL_PRODUCTION_HOST }} 'sudo chown -fR www-data:www-data /tmp/Personal'
        shell: bash

      - name: Swap new with old
        run: ssh admin@${{ secrets.PERSONAL_PRODUCTION_HOST }} 'sudo mv /var/www/personal /tmp/personal.bak && sudo mv /tmp/Personal /var/www/personal'
        shell: bash

      - name: Clean up
        run: ssh admin@${{ secrets.PERSONAL_PRODUCTION_HOST }} 'sudo rm -fR /tmp/personal.bak; sudo rm -fR /tmp/Personal.tar.bz2'
        shell: bash
