name: Run Tests (v2.1.x)

on:
  push:
    branches: 'v2.1.*'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      # Checkout dashboard-revcatch project
      - uses: actions/checkout@v3

      - uses: browser-actions/setup-chrome@v1

      - uses: ./.github/actions/build
        with:
          env: testing
          php-version: '8.2.7'
          node-version: '18.16.0'

      - name: Run php tests
        run: vendor/bin/phpunit
        shell: bash

      - name: Run admin tests
        run: cd resources/admin_ui && ./node_modules/\@angular/cli/bin/ng.js test --browsers ChromeHeadless